# Використовуємо базовий образ з підтримкою Bash
FROM ubuntu

RUN apt-get update && apt-get install -y curl

# Копіюємо скрипт в контейнер
COPY check_web_server.sh /check_web_server.sh

# Встановлюємо права на виконання для скрипту
RUN chmod +x /check_web_server.sh

# Виконуємо команду для запуску скрипту в контейнері
CMD ["/bin/bash", "-c", "/check_web_server.sh"]